# Generated by Django 6.1 on 2026-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BatteryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('soc', models.FloatField(help_text='State of charge, percentage 0-100')),
                ('charge_power', models.FloatField(default=0, help_text='kW, positive=charging')),
                ('discharge_power', models.FloatField(default=0, help_text='kW, positive=discharging')),
                ('health_indicator', models.FloatField(help_text='Percentage 0-100, battery health')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EnergyDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source_selection', models.CharField(choices=[('solar', 'Solar'), ('wind', 'Wind'), ('battery', 'Battery'), ('grid', 'Grid'), ('mixed', 'Mixed')], max_length=20)),
                ('battery_action', models.CharField(choices=[('charge', 'Charge'), ('discharge', 'Discharge'), ('idle', 'Idle')], max_length=20)),
                ('grid_action', models.CharField(choices=[('import', 'Import'), ('export', 'Export'), ('none', 'None')], max_length=20)),
                ('reason', models.TextField(help_text='Explainable reason for this decision')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When forecast was generated')),
                ('target_time', models.DateTimeField(db_index=True, help_text='Time being forecasted')),
                ('predicted_solar', models.FloatField(blank=True, null=True)),
                ('predicted_wind', models.FloatField(blank=True, null=True)),
                ('predicted_load', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GenerationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('solar_generation', models.FloatField(help_text='kW')),
                ('wind_generation', models.FloatField(help_text='kW')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('consumption', models.FloatField(help_text='kW')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(help_text='Scenario input parameters as JSON')),
                ('results', models.JSONField(blank=True, help_text='Scenario output results as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(help_text='Celsius')),
                ('humidity', models.FloatField(help_text='Percentage')),
                ('cloud_cover', models.FloatField(help_text='Percentage 0-100')),
                ('wind_speed', models.FloatField(help_text='m/s')),
                ('irradiance', models.FloatField(help_text='W/m^2')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
